### PR TITLE
Added bfNavigationController to NSViewController category.

### PR DESCRIPTION
**Pull request by ptwohig**
Heiko,

First of all, this is a great pod and thanks for taking the time to put it together and share with the world.  However, I noticed that out of the box there are two things missing from this implementation that I would like to add.
- The BFNavigationController does not seem to establish the parent/child linkage as it should.  I added code to support that.
- It would be nice to add a category to NSViewController that allows it to find the BFNavigationController reference.

I added code that does both of those things, as well as rigged up the example code to show that it works.  Please let me know if this pull request works for you!

Cheers,
Patrick.

### CODE REVIEW

**Comment by bfolder** [comment]
Hey Patrick,
what about the property "bfNavigationController". Is there a reason why you prefix it? Wouldn't it be nicer without prefix? Maybe I'm overlooking a naming clash!?

Heiko

**Comment by ptwohig** [comment]
Heiko,

Just as a matter of good practice, I usually prefix anything that goes into a category.  There's no actual need for it to be that way.  Should I change it and update the request?

Cheers,
Patrick.

**Comment by ptwohig** [comment]
Ha.  Looks like I wasn't the first to want this added.  Just looked at the other PRs.

**Comment by bfolder** [comment]
Yep. I see that. 
The problem with the last PR was that the guy removed the "respondsToSelector:" checks. The code may crash under certain circumstances. 

Anyway. Your code seems to call some 10.10 methods and deployment Target is 10.7. :(

Heiko

**Comment by ptwohig** [comment]
I come from iOS and I hadn't realized that the parenting of view controllers was 10.0 and higher.  How about I rework to check properly and then update the category?

**Comment by bfolder** [comment]
I merged the solution you provided with PR #1. Please have a look at https://github.com/bfolder/BFNavigationController/tree/parent-navigation and tell me if this behaves like you expect it to.

Heiko

**Pull request closed without merging**
